/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//audio/': RouteRecordInfo<'//audio/', '/audio', Record<never, never>, Record<never, never>>,
    '//audio/generate': RouteRecordInfo<'//audio/generate', '/audio/generate', Record<never, never>, Record<never, never>>,
    '//avatar': RouteRecordInfo<'//avatar', '/avatar', Record<never, never>, Record<never, never>>,
    '//duration-code': RouteRecordInfo<'//duration-code', '/duration-code', Record<never, never>, Record<never, never>>,
    '//editor/blueprint': RouteRecordInfo<'//editor/blueprint', '/editor/blueprint', Record<never, never>, Record<never, never>>,
    '//editor/copywriter': RouteRecordInfo<'//editor/copywriter', '/editor/copywriter', Record<never, never>, Record<never, never>>,
    '//editor/hint': RouteRecordInfo<'//editor/hint', '/editor/hint', Record<never, never>, Record<never, never>>,
    '//editor/scene': RouteRecordInfo<'//editor/scene', '/editor/scene', Record<never, never>, Record<never, never>>,
    '//editor/scene-avatar-location': RouteRecordInfo<'//editor/scene-avatar-location', '/editor/scene-avatar-location', Record<never, never>, Record<never, never>>,
    '//editor.[[projectId]]': RouteRecordInfo<'//editor.[[projectId]]', '/editor/:projectId?', { projectId?: ParamValueZeroOrOne<true> }, { projectId?: ParamValueZeroOrOne<false> }>,
    '//project': RouteRecordInfo<'//project', '/project', Record<never, never>, Record<never, never>>,
    '//task': RouteRecordInfo<'//task', '/task', Record<never, never>, Record<never, never>>,
    '//video': RouteRecordInfo<'//video', '/video', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
